name: Publish Resume

on: push

defaults:
  run:
    working-directory: .

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add version
        run: |
          fileName="resume.tex"
          echo "Substituting version number ${GITHUB_SHA::7} in file $fileName"
          sed -i -e "s/version/${GITHUB_SHA::7}/" $fileName
          echo ${GITHUB_SHA::7} > version.txt

      - name: Convert to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ResumeSHA
          path: |
            resume.pdf
            version.txt
